### PR TITLE
Logger rewrite

### PR DESCRIPTION
**Pull request by Teitoku**
Drop in logger, rewritten to be more extensible (albeit longer).
Rudimentary support for templating through reflection, allowing custom logging by the end user. This also allows everything to be easily serialized for other formats.

Titles might have been changed a little, but the order of CSV entries should be the same.

Moderately tested, but it looks like sortie logging is broken (even on your latest).

### CODE REVIEW

**Comment by Yuubari** [comment]
I apologise but I'm going to reject this pull request. First of all it does not merge cleanly (see [AppVeyor log](https://ci.appveyor.com/project/Yuubari/kancolleviewer/build/1.0.22)). Second, Logger.cs will be removed completely very, very soon.

**Comment by Teitoku** [comment]
Why is Logger.cs getting removed?

Also, sorry about the merge errors. I wrote it in VS2015 (which uses C# 6.0). Looks like there were some language changes. Might want to set the default build language to C# 5.0 in the projects.

**Comment by Yuubari** [comment]
The logging functionality is now implemented in a plug-in. There is no real reason to keep it in the main code, as it's not a required feature, and having it in a plug-in serves to illustrate how to implement a logging plug-in, letting weird people do whatever they want and make, e. g., plug-ins that log to a remote server.

The current implementation of the plug-in is feature incomplete and requires localisation, so I don't consider it production ready.

**Comment by Teitoku** [comment]
The idea was that eventually this would get ported to a plug-in, but I didn't see a logging plug-in being developed here or upstream (since the branch wasn't made until 3 days ago). I decided to merge this in since it looked like no one was maintaining the logger and this code was written prior to Grabacr implementing plugin support. Given that I don't know Japanese or C#, I was going to hold off porting it to a plugin until I figured out how KCV worked.

Most of the reflection support was put in in preparation to make it a plugin upstream, since it would allow the same code on both versions of KCV, but merely have different configuration files to log Japanese or English. (also so I could properly redo remote logging).

Given that you're working on it, let me know if you want help working on it. If you can explain the plugin API, I should have no problem implementing some of the logger.

**Pull request closed without merging**
